import { readdirSync, readFileSync, writeFileSync } from "node:fs";

const generatedDir = new URL("../src/generated/", import.meta.url);
const svgDir = new URL("../vendor/weather/svg/", import.meta.url);
const legendFile = new URL("../vendor/weather/legend.csv", import.meta.url);

const normalise = (value) => value.replace(/[^a-z0-9]/gi, "").toLowerCase();

const symbolCodes = readdirSync(svgDir)
  .filter((file) => file.endsWith(".svg"))
  .map((file) => file.slice(0, -4))
  .sort();

const barrel = readFileSync(new URL("index.ts", generatedDir), "utf8");
const componentsByNormalisedName = new Map(
  [...barrel.matchAll(/export \{ default as (\w+) \}/g)].map(([, name]) => [
    normalise(name),
    name,
  ]),
);

const pairs = symbolCodes.map((code) => {
  const component = componentsByNormalisedName.get(normalise(code));

  if (!component) throw new Error(`No generated component for "${code}"`);

  return [code, component];
});

const descriptions = readFileSync(legendFile, "utf8")
  .trim()
  .split("\n")
  .slice(1)
  .map((line) => line.split(","))
  .map(([id, english]) => [id.trim(), english.trim()]);

const contents = `// Generated by scripts/generate-lookup.mjs. Do not edit.
import type { FC, SVGProps } from "react";
import { ${pairs.map(([, component]) => component).join(", ")} } from "./index";

export const SYMBOL_CODES = [
${symbolCodes.map((code) => `  "${code}",`).join("\n")}
] as const;

export type SymbolCode = (typeof SYMBOL_CODES)[number];

export const iconsBySymbol: Record<SymbolCode, FC<SVGProps<SVGSVGElement>>> = {
${pairs.map(([code, component]) => `  "${code}": ${component},`).join("\n")}
};

export const symbolDescriptions: Record<string, string> = {
${descriptions.map(([id, english]) => `  "${id}": "${english}",`).join("\n")}
};
`;

writeFileSync(new URL("lookup.ts", generatedDir), contents);
