---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: data/galleries.json
  label: Galleries
- type: document
  path: data/landing.json
  label: Landing page
- type: directory
  path: data/_news
  label: News
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: heading
  label: About
- type: document
  path: data/safety.json
  label: Safety
- type: document
  path: data/governance.json
  label: Governance
- type: heading
  label: Regatta
- type: document
  path: data/regatta.json
  label: Regatta
- type: document
  path: data/regatta-location.json
  label: Find the regatta
upload_dir: public/assets
public_path: "/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
