backend:
  name: github
  repo: willkerry/sudbury-next-netlifycms
media_folder: static/img
editor:
  preview: false
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Club Officers", name: "clubOfficers", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
  - label: "News"
    name: "news"
    label_singular: Story
    folder: "data/_news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: true,
          date_format: "D MMMM YYYY",
          time_format: false,
        }
      - {
          label: "Main image",
          name: "coverImage",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown", required: true }
  - label: "About"
    name: "about"
    files:
      - label: "Governance"
        name: "governance"
        file: "data/governance.json"
        fields:
          - label: Club Officers
            name: officers
            allow_add: true
            label_singular: club officer
            minimize_collapsed: true
            hint: "Club officers are displayed in the order defined here."
            summary: "{{fields.name}}, {{fields.role}}"
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Role, name: role, widget: string }
              - {
                  label: "Vacant",
                  name: "vacant",
                  widget: "boolean",
                  default: false,
                  hint: "Display a ‘TBA’ icon instead of the officer’s name. "
                }
          - label: Committees
            name: committees
            allow_add: true
            label_singular: committee
            minimize_collapsed: true
            widget: list
            summary: "{{fields.name}}"
            hint: "Committees and committee members are displayed in the order defined here."
            fields:
              - { label: Committee name, name: name, widget: string }
              - { label: Description, name: description, widget: text }
              - label: Sitting officers
                name: officers
                allow_add: true
                label_singular: committee
                minimize_collapsed: true
                widget: list
                required: false
                hint: "A list of comma-separated terms, e.g. Chairman, Secretary, Treasurer"

          - {
              label: President,
              name: presidentDescription,
              widget: string,
              hint: "A sentence that describes the president’s role.",
            }
          - {
              label: Vice-president,
              name: vicePresidentDescription,
              widget: string,
              hint: "A sentence that describes the vice-presidents’ roles.",
            }
          - label: Vice-Presidents
            name: vicePresidents
            allow_add: true
            label_singular: Vice-President
            minimize_collapsed: true
            widget: list
            summary: "{{fields.firstName}} {{fields.surname}}"
            hint: "Vice-Presidents’ names are displayed alphabetically by surname on the website."
            fields:
              - { label: First name, name: firstName, widget: string }
              - { label: Surname, name: surname, widget: string }

          - label: Trustees
            name: trustees
            allow_add: true
            label_singular: trustee
            minimize_collapsed: true
            widget: list
            summary: "{{fields.firstName}} {{fields.surname}}"
            hint: "Trustees’ names are displayed alphabetically by surname on the website."
            fields:
              - { label: First name, name: firstName, widget: string }
              - { label: Surname, name: surname, widget: string }
          - label: Document Groups
            name: documents
            allow_add: true
            label_singular: document group
            minimize_collapsed: true
            widget: list
            summary: "{{fields.group}}"
            hint: "Document groups and the documents within them are displayed in the order defined here."
            fields:
              - { label: Group name, name: group, widget: string }
              - label: Documents
                name: items
                allow_add: true
                label_singular: document
                minimize_collapsed: true
                widget: list
                summary: "{{fields.name}}"
                fields:
                  - { label: Document name, name: name, widget: string }
                  - {
                      label: Document,
                      name: href,
                      widget: file,
                      hint: Upload or link to PDF version of the document.,
                    }
      - label: "Safety"
        name: "safety"
        file: "content/safety.json"
        fields:
          - label: River safety status
            name: status
            widget: object
            collapsed: true
            fields:
              - {
                  label: Disable?,
                  name: disable,
                  widget: boolean,
                  default: false,
                }
              - { label: Title, name: title, widget: string }
              - { label: Body, name: body, widget: text }
              - {
                  label: Severity,
                  name: severity,
                  widget: select,
                  options: ["Green", "Amber", "Red"],
                }
          - label: Safety Notices
            name: safety
            allow_add: true
            label_singular: safety notice
            minimize_collapsed: true
            summary: "{{fields.subject}}"
            widget: list
            fields:
              - { label: Subject, name: subject, widget: string }
              - {
                  label: Description,
                  name: description,
                  widget: markdown,
                  buttons: ["bulleted-list", "link"],
                  editor_components: [""],
                }
              - label: "Date updated"
                name: "date"
                widget: "datetime"
                default: ""
                date_format: "DD/MM/YYYY"
                time_format: "HH:mm"
                format: "LLL"
                required: false
                picker_utc: false
              - { label: File, name: file, widget: file, required: false }
